config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"


 	resources :questions
 	root 'questions#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	
	validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/answer.rb
class Answer < ApplicationRecord
	validates :content, presence: true
	belongs_to :user
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/only_superadmin_authorization.rb
class OnlySuperadminAuthorization < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    if user != nil && user.superadmin?
      return true
    end
    return false
  end

end

app/models/question.rb
class Question < ApplicationRecord
	validates :title, presence: true
	belongs_to :user
	has_one :answer
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :answers
  has_many :questions

  enum role: [:student, :mentor, :superadmin]

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@answer = current_user.answers.new(answer_params)
		@answer.question_id = params[:question_id]
		if @answer.save
			flash[:success] = "Your answer was successfully created"
		else
			flash[:error] = "There was an error saving your answer"
		end
		redirect_back(fallback_location: root_path)
	end

	private

	def answer_params
		params.require(:answer).permit(:content)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit
  protect_from_forgery with: :exception

 	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  def user_not_authorized(exception = nil)
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		if current_user
			@question = Question.new
			@questions = Question.all
		else
			redirect_to sign_in_path
		end
	end

	def show
		@question = Question.find(params[:id])
		@answer = 
			if @question.answer != nil
				@question.answer
			else
				Answer.new
			end
	end

	def create
		@question = current_user.questions.new(question_params)
		authorize @question
		if @question.save
			flash[:success] = "Your question was successfully submitted!"
			redirect_to root_path
		else	
			flash[:error] = "There was an error in submitting your question!"
			redirect_to root_path
		end
	end

	private

	def question_params
		params.require(:question).permit(:title, :content)
	end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def create
		@user = User.new(user_params)

		if @user.save 
			flash[:success] = "You account have been created"
			sign_in @user
			redirect_back_or url_after_create
		else
			flash[:error] = "There was an error in creating your account"
			render template: "users/new"
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password) 
	end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<div>
<%= form.text_field :content, type: 'text', class: 'form-control', placeholder: 'Type your Answer here' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NextOverflow</title>
    <%= csrf_meta_tags %>
 		
   	<!--Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <h2><%= link_to ('Next Overflow'), root_path %> </h2>
      <div id="header">
        <% if signed_in? %>
          <%= button_to 'Sign out', sign_out_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign in', sign_in_path %>
        <% end %>
      </div>

    	<% flash.each do |key, value| -%>
        <div id="flash_<%= key %>"><%=h value %></div>
      <% end %>
      
      <%= yield %>

    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div>
<%= form.text_field :title, type: 'text', class: 'form-control', placeholder: 'Title' %>
</div>
<div>
<%= form.text_area :content, type: 'text', class: 'form-control', placeholder: 'Content' %>
</div>

app/views/questions/_question_modal.erb
<div tabindex="-1" class="modal fade" id="question-modal" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header pmd-modal-bordered">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h2 class="pmd-card-title-text">Post a Question</h2>
      </div>
      <div class="modal-body">
        <%= form_for @question, html: {class: 'form-horizontal'} do |form| %>
          <div class="form-group pmd-textfield pmd-textfield-floating-label">
            <%= form.label :title, class: 'control-label' %>
            <%= form.text_field :title, type: 'text', class: 'form-control mat-input' %>
            <span class="help-text">Input is required!</span> 
          </div>
          <div class="form-group pmd-textfield pmd-textfield-floating-label">
            <%= form.label :content, class: 'control-label' %>
            <%= form.text_area :content, type: 'text', class: 'form-control mat-input' %>
          </div>
          <div class="pmd-modal-action">
            <%= form.submit 'Ask Question', class: 'btn pmd-ripple-effect btn-primary' %> 
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<h2> Welcome to Next Overflow </h2>

<h4> Ask a question </h4>

<div class="row">
	<div class="col-md-4">	
		<div class="form-inline">
			<div class="form-group">
				<%= text_field_tag :search, params[:search], placeholder: "Search Questions", class: 'form-control'%>
				<%= link_to "Ask a question", "#question-modal", 'data-toggle': 'modal', class: 'btn pmd-ripple-effect btn-primary pmd-z-depth', id: 'askaquestion' %>
			</div>
		</div>
	</div>
</div>



	<%= render partial: "questions/question_modal", layout: false %>


<!-- <div class="row">
	<%#= form_for @question do |form| %>
		<%#= render partial: '/questions/form', object: form %>
		<div>
			<%#= form.submit %>
		</div>
	<%# end %>
</div> -->

<br>
<br>


<% @questions.each do |x| %>
		<%= x.title %>

		<%= x.content %>

		<% unless current_user.student? %>
			<%= x.user.name %>
		<% end %>
<% end %>

app/views/questions/show.html.erb
<br>
<br>

<%= @question.title %>
<%= @question.content %>

<br>

<% if current_user.student? %>
	<p> Posted by Anonymous </p>
<% else %>
	<p> Posted by <%= @question.user.name %> </p>
<% end %>

<% if @answer.id != nil %>
	<p> Answer: </p>

	<p><%= @answer.content %></p>
	<p><%= @answer.user.name %></p>
<% end %>

<% if current_user.mentor? && @answer.id == nil %>
	<%= form_for @answer do |form| %>
		<%= hidden_field_tag 'question_id', @question.id %>
		<%= render partial: '/answers/form', object: form %>
		<%= form.submit 'Answer' %>
	<% end %>
<% end %>			

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>